import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/component/ReactQueryProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className="bg-gray-100">
                <ReactQueryProvider>{children}</ReactQueryProvider>
                <Toaster />
            </body>
        </html>
    );
}
